// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice =
  | ImageBannerSlice
  | CardGridSlice
  | ImageAndBulletListSlice
  | FeatureGridSlice
  | ImageAndAccordionRowSlice
  | FeatureRowSlice
  | ImageSliderSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * Link field in *Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Label field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *Settings → Navigation Menu*
 */
export interface SettingsDocumentDataNavigationMenuItem {
  /**
   * Label field in *Settings → Navigation Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation_menu[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Settings → Navigation Menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation_menu[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Settings → Social Media*
 */
export interface SettingsDocumentDataSocialMediaItem {
  /**
   * Icon field in *Settings → Social Media*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_media[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<"Facebook" | "Instagram" | "LinkedIn">;

  /**
   * Link field in *Settings → Social Media*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_media[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Settings → Addresses*
 */
export interface SettingsDocumentDataAddressesItem {
  /**
   * Plz field in *Settings → Addresses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.addresses[].plz
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  plz: prismic.KeyTextField;

  /**
   * Street field in *Settings → Addresses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.addresses[].street
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  street: prismic.KeyTextField;

  /**
   * Town field in *Settings → Addresses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.addresses[].town
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  town: prismic.KeyTextField;

  /**
   * Name field in *Settings → Addresses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.addresses[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Fallback Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.fallback_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  fallback_image: prismic.ImageField<never>;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;

  /**
   * Navigation Menu field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation_menu[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation_menu: prismic.GroupField<
    Simplify<SettingsDocumentDataNavigationMenuItem>
  >;

  /**
   * Social Media field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_media[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_media: prismic.GroupField<
    Simplify<SettingsDocumentDataSocialMediaItem>
  >;

  /**
   * Addresses field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.addresses[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  addresses: prismic.GroupField<Simplify<SettingsDocumentDataAddressesItem>>;

  /**
   * Phone Number field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.phone_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone_number: prismic.KeyTextField;

  /**
   * E-Mail field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Copyright field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.copyright
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copyright: prismic.KeyTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes = PageDocument | SettingsDocument;

/**
 * Primary content in *CardGrid → Primary*
 */
export interface CardGridSliceDefaultPrimary {
  /**
   * Heading field in *CardGrid → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *CardGrid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Main Image field in *CardGrid → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid.primary.main_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  main_image: prismic.ImageField<never>;
}

/**
 * Primary content in *CardGrid → Items*
 */
export interface CardGridSliceDefaultItem {
  /**
   * Name field in *CardGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Quote field in *CardGrid → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid.items[].quote
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote: prismic.RichTextField;

  /**
   * Image field in *CardGrid → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for CardGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CardGridSliceDefaultPrimary>,
  Simplify<CardGridSliceDefaultItem>
>;

/**
 * Slice variation for *CardGrid*
 */
type CardGridSliceVariation = CardGridSliceDefault;

/**
 * CardGrid Shared Slice
 *
 * - **API ID**: `card_grid`
 * - **Description**: CardGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardGridSlice = prismic.SharedSlice<
  "card_grid",
  CardGridSliceVariation
>;

/**
 * Primary content in *FeatureGrid → Primary*
 */
export interface FeatureGridSliceDefaultPrimary {
  /**
   * Heading field in *FeatureGrid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Subheading field in *FeatureGrid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;
}

/**
 * Primary content in *FeatureGrid → Items*
 */
export interface FeatureGridSliceDefaultItem {
  /**
   * Heading field in *FeatureGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *FeatureGrid → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Icon field in *FeatureGrid → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<
    "socialCare" | "machineLearning" | "education" | "research"
  >;
}

/**
 * Default variation for FeatureGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeatureGridSliceDefaultPrimary>,
  Simplify<FeatureGridSliceDefaultItem>
>;

/**
 * Slice variation for *FeatureGrid*
 */
type FeatureGridSliceVariation = FeatureGridSliceDefault;

/**
 * FeatureGrid Shared Slice
 *
 * - **API ID**: `feature_grid`
 * - **Description**: FeatureGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureGridSlice = prismic.SharedSlice<
  "feature_grid",
  FeatureGridSliceVariation
>;

/**
 * Primary content in *FeatureRow → Primary*
 */
export interface FeatureRowSliceDefaultPrimary {
  /**
   * Heading field in *FeatureRow → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_row.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Primary content in *FeatureRow → Items*
 */
export interface FeatureRowSliceDefaultItem {
  /**
   * Icon field in *FeatureRow → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_row.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<
    "healthcare" | "competence" | "community" | "networking"
  >;

  /**
   * Heading field in *FeatureRow → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_row.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *FeatureRow → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_row.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for FeatureRow Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureRowSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeatureRowSliceDefaultPrimary>,
  Simplify<FeatureRowSliceDefaultItem>
>;

/**
 * Slice variation for *FeatureRow*
 */
type FeatureRowSliceVariation = FeatureRowSliceDefault;

/**
 * FeatureRow Shared Slice
 *
 * - **API ID**: `feature_row`
 * - **Description**: FeatureRow
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureRowSlice = prismic.SharedSlice<
  "feature_row",
  FeatureRowSliceVariation
>;

/**
 * Primary content in *ImageAndAccordionRow → Primary*
 */
export interface ImageAndAccordionRowSliceDefaultPrimary {
  /**
   * Heading field in *ImageAndAccordionRow → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_accordion_row.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Subheading field in *ImageAndAccordionRow → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_accordion_row.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;

  /**
   * Image field in *ImageAndAccordionRow → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_accordion_row.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *ImageAndAccordionRow → Items*
 */
export interface ImageAndAccordionRowSliceDefaultItem {
  /**
   * Heading field in *ImageAndAccordionRow → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_accordion_row.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *ImageAndAccordionRow → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_accordion_row.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for ImageAndAccordionRow Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageAndAccordionRowSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageAndAccordionRowSliceDefaultPrimary>,
  Simplify<ImageAndAccordionRowSliceDefaultItem>
>;

/**
 * Slice variation for *ImageAndAccordionRow*
 */
type ImageAndAccordionRowSliceVariation = ImageAndAccordionRowSliceDefault;

/**
 * ImageAndAccordionRow Shared Slice
 *
 * - **API ID**: `image_and_accordion_row`
 * - **Description**: ImageAndAccordionRow
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageAndAccordionRowSlice = prismic.SharedSlice<
  "image_and_accordion_row",
  ImageAndAccordionRowSliceVariation
>;

/**
 * Primary content in *ImageAndBulletList → Primary*
 */
export interface ImageAndBulletListSliceDefaultPrimary {
  /**
   * Image field in *ImageAndBulletList → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_bullet_list.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *ImageAndBulletList → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_bullet_list.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Subheading field in *ImageAndBulletList → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_bullet_list.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;

  /**
   * Card Heading field in *ImageAndBulletList → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_bullet_list.primary.card_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  card_heading: prismic.KeyTextField;

  /**
   * Card Description field in *ImageAndBulletList → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_bullet_list.primary.card_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  card_description: prismic.KeyTextField;

  /**
   * Button Text field in *ImageAndBulletList → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_bullet_list.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *ImageAndBulletList → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_bullet_list.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Primary content in *ImageAndBulletList → Items*
 */
export interface ImageAndBulletListSliceDefaultItem {
  /**
   * Icon field in *ImageAndBulletList → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_bullet_list.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<"Plus" | "Bell" | "Camera" | "Book">;

  /**
   * Icon Description field in *ImageAndBulletList → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_bullet_list.items[].icon_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  icon_description: prismic.KeyTextField;
}

/**
 * Default variation for ImageAndBulletList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageAndBulletListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageAndBulletListSliceDefaultPrimary>,
  Simplify<ImageAndBulletListSliceDefaultItem>
>;

/**
 * Slice variation for *ImageAndBulletList*
 */
type ImageAndBulletListSliceVariation = ImageAndBulletListSliceDefault;

/**
 * ImageAndBulletList Shared Slice
 *
 * - **API ID**: `image_and_bullet_list`
 * - **Description**: ImageAndBulletList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageAndBulletListSlice = prismic.SharedSlice<
  "image_and_bullet_list",
  ImageAndBulletListSliceVariation
>;

/**
 * Primary content in *ImageBanner → Items*
 */
export interface ImageBannerSliceDefaultItem {
  /**
   * Image field in *ImageBanner → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_banner.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ImageBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ImageBannerSliceDefaultItem>
>;

/**
 * Slice variation for *ImageBanner*
 */
type ImageBannerSliceVariation = ImageBannerSliceDefault;

/**
 * ImageBanner Shared Slice
 *
 * - **API ID**: `image_banner`
 * - **Description**: ImageBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageBannerSlice = prismic.SharedSlice<
  "image_banner",
  ImageBannerSliceVariation
>;

/**
 * Primary content in *ImageSlider → Primary*
 */
export interface ImageSliderSliceDefaultPrimary {
  /**
   * Button Link field in *ImageSlider → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Button Label field in *ImageSlider → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Title field in *ImageSlider → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Sub Heading 1 field in *ImageSlider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.primary.sub_heading_1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading_1: prismic.RichTextField;

  /**
   * Sub Heading 2 field in *ImageSlider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.primary.sub_heading_2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading_2: prismic.RichTextField;

  /**
   * Sub Heading 3 field in *ImageSlider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.primary.sub_heading_3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading_3: prismic.RichTextField;
}

/**
 * Primary content in *ImageSlider → Items*
 */
export interface ImageSliderSliceDefaultItem {
  /**
   * Image field in *ImageSlider → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ImageSlider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSliderSliceDefaultPrimary>,
  Simplify<ImageSliderSliceDefaultItem>
>;

/**
 * Slice variation for *ImageSlider*
 */
type ImageSliderSliceVariation = ImageSliderSliceDefault;

/**
 * ImageSlider Shared Slice
 *
 * - **API ID**: `image_slider`
 * - **Description**: ImageSlider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliderSlice = prismic.SharedSlice<
  "image_slider",
  ImageSliderSliceVariation
>;

/**
 * Primary content in *RichText → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      SettingsDocumentDataNavigationMenuItem,
      SettingsDocumentDataSocialMediaItem,
      SettingsDocumentDataAddressesItem,
      AllDocumentTypes,
      CardGridSlice,
      CardGridSliceDefaultPrimary,
      CardGridSliceDefaultItem,
      CardGridSliceVariation,
      CardGridSliceDefault,
      FeatureGridSlice,
      FeatureGridSliceDefaultPrimary,
      FeatureGridSliceDefaultItem,
      FeatureGridSliceVariation,
      FeatureGridSliceDefault,
      FeatureRowSlice,
      FeatureRowSliceDefaultPrimary,
      FeatureRowSliceDefaultItem,
      FeatureRowSliceVariation,
      FeatureRowSliceDefault,
      ImageAndAccordionRowSlice,
      ImageAndAccordionRowSliceDefaultPrimary,
      ImageAndAccordionRowSliceDefaultItem,
      ImageAndAccordionRowSliceVariation,
      ImageAndAccordionRowSliceDefault,
      ImageAndBulletListSlice,
      ImageAndBulletListSliceDefaultPrimary,
      ImageAndBulletListSliceDefaultItem,
      ImageAndBulletListSliceVariation,
      ImageAndBulletListSliceDefault,
      ImageBannerSlice,
      ImageBannerSliceDefaultItem,
      ImageBannerSliceVariation,
      ImageBannerSliceDefault,
      ImageSliderSlice,
      ImageSliderSliceDefaultPrimary,
      ImageSliderSliceDefaultItem,
      ImageSliderSliceVariation,
      ImageSliderSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
    };
  }
}
