// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice =
  | FullWidthAccordionSlice
  | ApplicationCardSlice
  | HeroBannerSlice
  | CenteredTextSlice
  | FullWidthImageSlice
  | ImageAndCallToActionSlice
  | TimeLineSlice
  | ImageBannerSlice
  | CardGridSlice
  | ImageAndBulletListSlice
  | FeatureGridSlice
  | ImageAndAccordionRowSlice
  | FeatureRowSlice
  | ImageSliderSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * Link field in *Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Label field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *Settings → Leistungen Menu*
 */
export interface SettingsDocumentDataLeistungenMenuItem {
  /**
   * Label field in *Settings → Leistungen Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.leistungen_menu[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Settings → Leistungen Menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.leistungen_menu[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Settings → Jobs Menu*
 */
export interface SettingsDocumentDataJobsMenuItem {
  /**
   * Label field in *Settings → Jobs Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.jobs_menu[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Settings → Jobs Menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.jobs_menu[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Settings → Social Media*
 */
export interface SettingsDocumentDataSocialMediaItem {
  /**
   * Icon field in *Settings → Social Media*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_media[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<"Facebook" | "Instagram" | "LinkedIn">;

  /**
   * Link field in *Settings → Social Media*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_media[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Settings → Addresses*
 */
export interface SettingsDocumentDataAddressesItem {
  /**
   * Plz field in *Settings → Addresses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.addresses[].plz
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  plz: prismic.KeyTextField;

  /**
   * Street field in *Settings → Addresses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.addresses[].street
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  street: prismic.KeyTextField;

  /**
   * Town field in *Settings → Addresses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.addresses[].town
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  town: prismic.KeyTextField;

  /**
   * Name field in *Settings → Addresses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.addresses[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Fallback Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.fallback_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  fallback_image: prismic.ImageField<never>;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;

  /**
   * Leistungen Menu field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.leistungen_menu[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  leistungen_menu: prismic.GroupField<
    Simplify<SettingsDocumentDataLeistungenMenuItem>
  >;

  /**
   * Jobs Menu field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.jobs_menu[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  jobs_menu: prismic.GroupField<Simplify<SettingsDocumentDataJobsMenuItem>>;

  /**
   * Social Media field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_media[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_media: prismic.GroupField<
    Simplify<SettingsDocumentDataSocialMediaItem>
  >;

  /**
   * Addresses field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.addresses[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  addresses: prismic.GroupField<Simplify<SettingsDocumentDataAddressesItem>>;

  /**
   * Phone Number field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.phone_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone_number: prismic.KeyTextField;

  /**
   * E-Mail field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Copyright field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.copyright
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copyright: prismic.KeyTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes = PageDocument | SettingsDocument;

/**
 * Primary content in *ApplicationCard → Primary*
 */
export interface ApplicationCardSliceDefaultPrimary {
  /**
   * Job Title field in *ApplicationCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: application_card.primary.job_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  job_title: prismic.KeyTextField;

  /**
   * Title Richtext field in *ApplicationCard → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: application_card.primary.title_richtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_richtext: prismic.RichTextField;

  /**
   * Address field in *ApplicationCard → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: application_card.primary.address
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  address: prismic.RichTextField;

  /**
   * Working Hours field in *ApplicationCard → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: application_card.primary.working_hours
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  working_hours: prismic.RichTextField;

  /**
   * Start Date field in *ApplicationCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: application_card.primary.start_date
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  start_date: prismic.KeyTextField;

  /**
   * Start Date Richtext field in *ApplicationCard → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: application_card.primary.start_date_richtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  start_date_richtext: prismic.RichTextField;

  /**
   * Address Image field in *ApplicationCard → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: application_card.primary.address_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  address_image: prismic.ImageField<never>;

  /**
   * Working Hours Image field in *ApplicationCard → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: application_card.primary.working_hours_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  working_hours_image: prismic.ImageField<never>;

  /**
   * Start Date Image field in *ApplicationCard → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: application_card.primary.start_date_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  start_date_image: prismic.ImageField<never>;
}

/**
 * Primary content in *ApplicationCard → Items*
 */
export interface ApplicationCardSliceDefaultItem {
  /**
   * Description field in *ApplicationCard → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: application_card.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for ApplicationCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ApplicationCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ApplicationCardSliceDefaultPrimary>,
  Simplify<ApplicationCardSliceDefaultItem>
>;

/**
 * Slice variation for *ApplicationCard*
 */
type ApplicationCardSliceVariation = ApplicationCardSliceDefault;

/**
 * ApplicationCard Shared Slice
 *
 * - **API ID**: `application_card`
 * - **Description**: ApplicationCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ApplicationCardSlice = prismic.SharedSlice<
  "application_card",
  ApplicationCardSliceVariation
>;

/**
 * Primary content in *ApplicationForm → Items*
 */
export interface ApplicationFormSliceDefaultItem {
  /**
   * Job Title field in *ApplicationForm → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: application_form.items[].job_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  job_title: prismic.KeyTextField;
}

/**
 * Default variation for ApplicationForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ApplicationFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ApplicationFormSliceDefaultItem>
>;

/**
 * Slice variation for *ApplicationForm*
 */
type ApplicationFormSliceVariation = ApplicationFormSliceDefault;

/**
 * ApplicationForm Shared Slice
 *
 * - **API ID**: `application_form`
 * - **Description**: ApplicationForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ApplicationFormSlice = prismic.SharedSlice<
  "application_form",
  ApplicationFormSliceVariation
>;

/**
 * Primary content in *CardGrid → Primary*
 */
export interface CardGridSliceDefaultPrimary {
  /**
   * Heading field in *CardGrid → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Heading RichText field in *CardGrid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid.primary.heading_richtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading_richtext: prismic.RichTextField;

  /**
   * Description field in *CardGrid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Main Image field in *CardGrid → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid.primary.main_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  main_image: prismic.ImageField<never>;
}

/**
 * Primary content in *CardGrid → Items*
 */
export interface CardGridSliceDefaultItem {
  /**
   * Name field in *CardGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Name Richtext field in *CardGrid → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid.items[].name_richtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name_richtext: prismic.RichTextField;

  /**
   * Quote field in *CardGrid → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid.items[].quote
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote: prismic.RichTextField;

  /**
   * Image field in *CardGrid → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for CardGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CardGridSliceDefaultPrimary>,
  Simplify<CardGridSliceDefaultItem>
>;

/**
 * Slice variation for *CardGrid*
 */
type CardGridSliceVariation = CardGridSliceDefault;

/**
 * CardGrid Shared Slice
 *
 * - **API ID**: `card_grid`
 * - **Description**: CardGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardGridSlice = prismic.SharedSlice<
  "card_grid",
  CardGridSliceVariation
>;

/**
 * Primary content in *CenteredText → Primary*
 */
export interface CenteredTextSliceDefaultPrimary {
  /**
   * Heading field in *CenteredText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: centered_text.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Heading Richtext field in *CenteredText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: centered_text.primary.heading_richtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading_richtext: prismic.RichTextField;

  /**
   * Subheading field in *CenteredText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: centered_text.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * Subheading Richtext field in *CenteredText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: centered_text.primary.subheading_richtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading_richtext: prismic.RichTextField;

  /**
   * Text field in *CenteredText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: centered_text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * BackgroundColor field in *CenteredText → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: default
   * - **API ID Path**: centered_text.primary.backgroundcolor
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundcolor: prismic.SelectField<
    "default" | "primary" | "secondary" | "secondary50" | "lightGray",
    "filled"
  >;
}

/**
 * Default variation for CenteredText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CenteredTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CenteredTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CenteredText*
 */
type CenteredTextSliceVariation = CenteredTextSliceDefault;

/**
 * CenteredText Shared Slice
 *
 * - **API ID**: `centered_text`
 * - **Description**: CenteredText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CenteredTextSlice = prismic.SharedSlice<
  "centered_text",
  CenteredTextSliceVariation
>;

/**
 * Primary content in *FeatureGrid → Primary*
 */
export interface FeatureGridSliceDefaultPrimary {
  /**
   * Heading field in *FeatureGrid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Subheading field in *FeatureGrid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;
}

/**
 * Primary content in *FeatureGrid → Items*
 */
export interface FeatureGridSliceDefaultItem {
  /**
   * Heading field in *FeatureGrid → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *FeatureGrid → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Icon field in *FeatureGrid → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Default variation for FeatureGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeatureGridSliceDefaultPrimary>,
  Simplify<FeatureGridSliceDefaultItem>
>;

/**
 * Primary content in *FeatureGrid → Primary*
 */
export interface FeatureGridSliceNoBackgroundImagesPrimary {
  /**
   * Heading field in *FeatureGrid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Subheading field in *FeatureGrid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;
}

/**
 * Primary content in *FeatureGrid → Items*
 */
export interface FeatureGridSliceNoBackgroundImagesItem {
  /**
   * Heading field in *FeatureGrid → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *FeatureGrid → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Icon field in *FeatureGrid → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * No Background Images variation for FeatureGrid Slice
 *
 * - **API ID**: `noBackgroundImages`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureGridSliceNoBackgroundImages = prismic.SharedSliceVariation<
  "noBackgroundImages",
  Simplify<FeatureGridSliceNoBackgroundImagesPrimary>,
  Simplify<FeatureGridSliceNoBackgroundImagesItem>
>;

/**
 * Slice variation for *FeatureGrid*
 */
type FeatureGridSliceVariation =
  | FeatureGridSliceDefault
  | FeatureGridSliceNoBackgroundImages;

/**
 * FeatureGrid Shared Slice
 *
 * - **API ID**: `feature_grid`
 * - **Description**: FeatureGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureGridSlice = prismic.SharedSlice<
  "feature_grid",
  FeatureGridSliceVariation
>;

/**
 * Primary content in *FeatureRow → Primary*
 */
export interface FeatureRowSliceDefaultPrimary {
  /**
   * Heading field in *FeatureRow → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_row.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Icon Backround Color field in *FeatureRow → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: lightGray
   * - **API ID Path**: feature_row.primary.icon_backround_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon_backround_color: prismic.SelectField<
    "lightGray" | "default" | "primary" | "secondary",
    "filled"
  >;
}

/**
 * Primary content in *FeatureRow → Items*
 */
export interface FeatureRowSliceDefaultItem {
  /**
   * Heading field in *FeatureRow → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_row.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *FeatureRow → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_row.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Icon field in *FeatureRow → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_row.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Default variation for FeatureRow Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureRowSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeatureRowSliceDefaultPrimary>,
  Simplify<FeatureRowSliceDefaultItem>
>;

/**
 * Slice variation for *FeatureRow*
 */
type FeatureRowSliceVariation = FeatureRowSliceDefault;

/**
 * FeatureRow Shared Slice
 *
 * - **API ID**: `feature_row`
 * - **Description**: FeatureRow
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureRowSlice = prismic.SharedSlice<
  "feature_row",
  FeatureRowSliceVariation
>;

/**
 * Primary content in *FullWidthAccordion → Primary*
 */
export interface FullWidthAccordionSliceDefaultPrimary {
  /**
   * Heading field in *FullWidthAccordion → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_accordion.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Primary content in *FullWidthAccordion → Items*
 */
export interface FullWidthAccordionSliceDefaultItem {
  /**
   * Heading field in *FullWidthAccordion → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_accordion.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Heading Richtext field in *FullWidthAccordion → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_accordion.items[].heading_richtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading_richtext: prismic.RichTextField;

  /**
   * Content field in *FullWidthAccordion → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_accordion.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for FullWidthAccordion Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullWidthAccordionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FullWidthAccordionSliceDefaultPrimary>,
  Simplify<FullWidthAccordionSliceDefaultItem>
>;

/**
 * Slice variation for *FullWidthAccordion*
 */
type FullWidthAccordionSliceVariation = FullWidthAccordionSliceDefault;

/**
 * FullWidthAccordion Shared Slice
 *
 * - **API ID**: `full_width_accordion`
 * - **Description**: FullWidthAccordion
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullWidthAccordionSlice = prismic.SharedSlice<
  "full_width_accordion",
  FullWidthAccordionSliceVariation
>;

/**
 * Primary content in *FullWidthImage → Primary*
 */
export interface FullWidthImageSliceDefaultPrimary {
  /**
   * Image field in *FullWidthImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * BackgroundColor field in *FullWidthImage → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_image.primary.backgroundcolor
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundcolor: prismic.SelectField<
    "hellgrün" | "grau" | "dunkelblau" | "graublau" | "weiß"
  >;
}

/**
 * Default variation for FullWidthImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullWidthImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FullWidthImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FullWidthImage*
 */
type FullWidthImageSliceVariation = FullWidthImageSliceDefault;

/**
 * FullWidthImage Shared Slice
 *
 * - **API ID**: `full_width_image`
 * - **Description**: FullWidthImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullWidthImageSlice = prismic.SharedSlice<
  "full_width_image",
  FullWidthImageSliceVariation
>;

/**
 * Primary content in *HeroBanner → Primary*
 */
export interface HeroBannerSliceDefaultPrimary {
  /**
   * Image field in *HeroBanner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *HeroBanner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Heading Richtext field in *HeroBanner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.heading_richtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading_richtext: prismic.RichTextField;

  /**
   * Subheading field in *HeroBanner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * Subheading Richtext field in *HeroBanner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.subheading_richtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading_richtext: prismic.RichTextField;

  /**
   * Link field in *HeroBanner → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Link Label field in *HeroBanner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;
}

/**
 * Text Center variation for HeroBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroBannerSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *HeroBanner → Primary*
 */
export interface HeroBannerSliceTextLeftPrimary {
  /**
   * Image field in *HeroBanner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *HeroBanner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Heading Richtext field in *HeroBanner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.heading_richtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading_richtext: prismic.RichTextField;

  /**
   * Subheading field in *HeroBanner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * Subheading Richtext field in *HeroBanner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.subheading_richtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading_richtext: prismic.RichTextField;

  /**
   * Link field in *HeroBanner → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Link Label field in *HeroBanner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;
}

/**
 * Text Left variation for HeroBanner Slice
 *
 * - **API ID**: `textLeft`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBannerSliceTextLeft = prismic.SharedSliceVariation<
  "textLeft",
  Simplify<HeroBannerSliceTextLeftPrimary>,
  never
>;

/**
 * Primary content in *HeroBanner → Primary*
 */
export interface HeroBannerSliceTextRightPrimary {
  /**
   * Image field in *HeroBanner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *HeroBanner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Heading Richtext field in *HeroBanner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.heading_richtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading_richtext: prismic.RichTextField;

  /**
   * Subheading field in *HeroBanner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * Subheading Richtext field in *HeroBanner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.subheading_richtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading_richtext: prismic.RichTextField;

  /**
   * Link field in *HeroBanner → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Link Label field in *HeroBanner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;
}

/**
 * Text Right variation for HeroBanner Slice
 *
 * - **API ID**: `textRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBannerSliceTextRight = prismic.SharedSliceVariation<
  "textRight",
  Simplify<HeroBannerSliceTextRightPrimary>,
  never
>;

/**
 * Slice variation for *HeroBanner*
 */
type HeroBannerSliceVariation =
  | HeroBannerSliceDefault
  | HeroBannerSliceTextLeft
  | HeroBannerSliceTextRight;

/**
 * HeroBanner Shared Slice
 *
 * - **API ID**: `hero_banner`
 * - **Description**: HeroBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBannerSlice = prismic.SharedSlice<
  "hero_banner",
  HeroBannerSliceVariation
>;

/**
 * Primary content in *ImageAndAccordionRow → Primary*
 */
export interface ImageAndAccordionRowSliceDefaultPrimary {
  /**
   * Heading field in *ImageAndAccordionRow → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_accordion_row.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Subheading field in *ImageAndAccordionRow → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_accordion_row.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;

  /**
   * Image field in *ImageAndAccordionRow → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_accordion_row.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * BackgroundColor field in *ImageAndAccordionRow → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: default
   * - **API ID Path**: image_and_accordion_row.primary.backgroundcolor
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundcolor: prismic.SelectField<
    "default" | "primary" | "secondary" | "lightGray" | "secondary50",
    "filled"
  >;
}

/**
 * Primary content in *ImageAndAccordionRow → Items*
 */
export interface ImageAndAccordionRowSliceDefaultItem {
  /**
   * Heading field in *ImageAndAccordionRow → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_accordion_row.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Heading Richtext field in *ImageAndAccordionRow → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_accordion_row.items[].heading_richtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading_richtext: prismic.RichTextField;

  /**
   * Description field in *ImageAndAccordionRow → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_accordion_row.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for ImageAndAccordionRow Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageAndAccordionRowSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageAndAccordionRowSliceDefaultPrimary>,
  Simplify<ImageAndAccordionRowSliceDefaultItem>
>;

/**
 * Slice variation for *ImageAndAccordionRow*
 */
type ImageAndAccordionRowSliceVariation = ImageAndAccordionRowSliceDefault;

/**
 * ImageAndAccordionRow Shared Slice
 *
 * - **API ID**: `image_and_accordion_row`
 * - **Description**: ImageAndAccordionRow
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageAndAccordionRowSlice = prismic.SharedSlice<
  "image_and_accordion_row",
  ImageAndAccordionRowSliceVariation
>;

/**
 * Primary content in *ImageAndBulletList → Primary*
 */
export interface ImageAndBulletListSliceDefaultPrimary {
  /**
   * Image field in *ImageAndBulletList → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_bullet_list.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *ImageAndBulletList → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_bullet_list.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Subheading field in *ImageAndBulletList → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_bullet_list.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;

  /**
   * Card Heading Richtext field in *ImageAndBulletList → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_bullet_list.primary.card_heading_richtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  card_heading_richtext: prismic.RichTextField;

  /**
   * Card Description Richtext field in *ImageAndBulletList → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_bullet_list.primary.card_description_richtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  card_description_richtext: prismic.RichTextField;

  /**
   * Button Text field in *ImageAndBulletList → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_bullet_list.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *ImageAndBulletList → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_bullet_list.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * BackgroundColor field in *ImageAndBulletList → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: default
   * - **API ID Path**: image_and_bullet_list.primary.backgroundcolor
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundcolor: prismic.SelectField<
    "default" | "primary" | "secondary" | "secondary50" | "lightGray",
    "filled"
  >;
}

/**
 * Primary content in *ImageAndBulletList → Items*
 */
export interface ImageAndBulletListSliceDefaultItem {
  /**
   * Icon field in *ImageAndBulletList → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_bullet_list.items[].iconimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  iconimage: prismic.ImageField<never>;

  /**
   * Description field in *ImageAndBulletList → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_bullet_list.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for ImageAndBulletList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageAndBulletListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageAndBulletListSliceDefaultPrimary>,
  Simplify<ImageAndBulletListSliceDefaultItem>
>;

/**
 * Slice variation for *ImageAndBulletList*
 */
type ImageAndBulletListSliceVariation = ImageAndBulletListSliceDefault;

/**
 * ImageAndBulletList Shared Slice
 *
 * - **API ID**: `image_and_bullet_list`
 * - **Description**: ImageAndBulletList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageAndBulletListSlice = prismic.SharedSlice<
  "image_and_bullet_list",
  ImageAndBulletListSliceVariation
>;

/**
 * Primary content in *ImageAndCallToAction → Primary*
 */
export interface ImageAndCallToActionSliceDefaultPrimary {
  /**
   * Image field in *ImageAndCallToAction → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_call_to_action.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *ImageAndCallToAction → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_call_to_action.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Heading Richtext field in *ImageAndCallToAction → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_call_to_action.primary.heading_richtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading_richtext: prismic.RichTextField;

  /**
   * description field in *ImageAndCallToAction → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_call_to_action.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Link field in *ImageAndCallToAction → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_call_to_action.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Link Label field in *ImageAndCallToAction → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_call_to_action.primary.link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;
}

/**
 * Default variation for ImageAndCallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageAndCallToActionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageAndCallToActionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageAndCallToAction*
 */
type ImageAndCallToActionSliceVariation = ImageAndCallToActionSliceDefault;

/**
 * ImageAndCallToAction Shared Slice
 *
 * - **API ID**: `image_and_call_to_action`
 * - **Description**: ImageAndCallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageAndCallToActionSlice = prismic.SharedSlice<
  "image_and_call_to_action",
  ImageAndCallToActionSliceVariation
>;

/**
 * Primary content in *ImageBanner → Items*
 */
export interface ImageBannerSliceDefaultItem {
  /**
   * Image field in *ImageBanner → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_banner.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ImageBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ImageBannerSliceDefaultItem>
>;

/**
 * Slice variation for *ImageBanner*
 */
type ImageBannerSliceVariation = ImageBannerSliceDefault;

/**
 * ImageBanner Shared Slice
 *
 * - **API ID**: `image_banner`
 * - **Description**: ImageBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageBannerSlice = prismic.SharedSlice<
  "image_banner",
  ImageBannerSliceVariation
>;

/**
 * Primary content in *ImageSlider → Primary*
 */
export interface ImageSliderSliceDefaultPrimary {
  /**
   * Title field in *ImageSlider → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Title Richtext field in *ImageSlider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.primary.title_richtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_richtext: prismic.RichTextField;

  /**
   * Sub Heading 1 field in *ImageSlider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.primary.sub_heading_1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading_1: prismic.RichTextField;

  /**
   * Sub Heading 2 field in *ImageSlider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.primary.sub_heading_2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading_2: prismic.RichTextField;

  /**
   * Sub Heading 3 field in *ImageSlider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.primary.sub_heading_3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading_3: prismic.RichTextField;

  /**
   * Button Link field in *ImageSlider → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Button Label field in *ImageSlider → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;
}

/**
 * Primary content in *ImageSlider → Items*
 */
export interface ImageSliderSliceDefaultItem {
  /**
   * Image field in *ImageSlider → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Text Top variation for ImageSlider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSliderSliceDefaultPrimary>,
  Simplify<ImageSliderSliceDefaultItem>
>;

/**
 * Primary content in *ImageSlider → Primary*
 */
export interface ImageSliderSliceTextBottomPrimary {
  /**
   * Title field in *ImageSlider → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Title Richtext field in *ImageSlider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.primary.title_richtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_richtext: prismic.RichTextField;

  /**
   * Sub Heading 1 field in *ImageSlider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.primary.sub_heading_1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading_1: prismic.RichTextField;

  /**
   * Sub Heading 2 field in *ImageSlider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.primary.sub_heading_2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading_2: prismic.RichTextField;

  /**
   * Sub Heading 3 field in *ImageSlider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.primary.sub_heading_3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading_3: prismic.RichTextField;

  /**
   * Button Link field in *ImageSlider → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Button Label field in *ImageSlider → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;
}

/**
 * Primary content in *ImageSlider → Items*
 */
export interface ImageSliderSliceTextBottomItem {
  /**
   * Image field in *ImageSlider → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Text Bottom variation for ImageSlider Slice
 *
 * - **API ID**: `textBottom`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliderSliceTextBottom = prismic.SharedSliceVariation<
  "textBottom",
  Simplify<ImageSliderSliceTextBottomPrimary>,
  Simplify<ImageSliderSliceTextBottomItem>
>;

/**
 * Primary content in *ImageSlider → Primary*
 */
export interface ImageSliderSliceTextCenterPrimary {
  /**
   * Title field in *ImageSlider → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Title Richtext field in *ImageSlider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.primary.title_richtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_richtext: prismic.RichTextField;

  /**
   * Sub Heading 1 field in *ImageSlider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.primary.sub_heading_1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading_1: prismic.RichTextField;

  /**
   * Sub Heading 2 field in *ImageSlider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.primary.sub_heading_2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading_2: prismic.RichTextField;

  /**
   * Sub Heading 3 field in *ImageSlider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.primary.sub_heading_3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading_3: prismic.RichTextField;

  /**
   * Button Link field in *ImageSlider → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Button Label field in *ImageSlider → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;
}

/**
 * Primary content in *ImageSlider → Items*
 */
export interface ImageSliderSliceTextCenterItem {
  /**
   * Image field in *ImageSlider → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Text Center variation for ImageSlider Slice
 *
 * - **API ID**: `textCenter`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliderSliceTextCenter = prismic.SharedSliceVariation<
  "textCenter",
  Simplify<ImageSliderSliceTextCenterPrimary>,
  Simplify<ImageSliderSliceTextCenterItem>
>;

/**
 * Slice variation for *ImageSlider*
 */
type ImageSliderSliceVariation =
  | ImageSliderSliceDefault
  | ImageSliderSliceTextBottom
  | ImageSliderSliceTextCenter;

/**
 * ImageSlider Shared Slice
 *
 * - **API ID**: `image_slider`
 * - **Description**: ImageSlider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliderSlice = prismic.SharedSlice<
  "image_slider",
  ImageSliderSliceVariation
>;

/**
 * Primary content in *TimeLine → Primary*
 */
export interface TimeLineSliceDefaultPrimary {
  /**
   * Heading field in *TimeLine → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: time_line.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *TimeLine → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: time_line.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *TimeLine → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: time_line.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *TimeLine → Items*
 */
export interface TimeLineSliceDefaultItem {
  /**
   * Heading field in *TimeLine → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: time_line.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Heading Richtext field in *TimeLine → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: time_line.items[].heading_richtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading_richtext: prismic.RichTextField;

  /**
   * Text field in *TimeLine → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: time_line.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for TimeLine Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimeLineSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TimeLineSliceDefaultPrimary>,
  Simplify<TimeLineSliceDefaultItem>
>;

/**
 * Slice variation for *TimeLine*
 */
type TimeLineSliceVariation = TimeLineSliceDefault;

/**
 * TimeLine Shared Slice
 *
 * - **API ID**: `time_line`
 * - **Description**: TimeLine
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimeLineSlice = prismic.SharedSlice<
  "time_line",
  TimeLineSliceVariation
>;

/**
 * Primary content in *Wheel → Primary*
 */
export interface WheelSliceDefaultPrimary {
  /**
   * Heading field in *Wheel → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: wheel.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *Wheel → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: wheel.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *Wheel → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: wheel.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Wheel → Items*
 */
export interface WheelSliceDefaultItem {
  /**
   * Heading field in *Wheel → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: wheel.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *Wheel → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: wheel.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Wheel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WheelSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WheelSliceDefaultPrimary>,
  Simplify<WheelSliceDefaultItem>
>;

/**
 * Slice variation for *Wheel*
 */
type WheelSliceVariation = WheelSliceDefault;

/**
 * Wheel Shared Slice
 *
 * - **API ID**: `wheel`
 * - **Description**: Wheel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WheelSlice = prismic.SharedSlice<"wheel", WheelSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      SettingsDocumentDataLeistungenMenuItem,
      SettingsDocumentDataJobsMenuItem,
      SettingsDocumentDataSocialMediaItem,
      SettingsDocumentDataAddressesItem,
      AllDocumentTypes,
      ApplicationCardSlice,
      ApplicationCardSliceDefaultPrimary,
      ApplicationCardSliceDefaultItem,
      ApplicationCardSliceVariation,
      ApplicationCardSliceDefault,
      ApplicationFormSlice,
      ApplicationFormSliceDefaultItem,
      ApplicationFormSliceVariation,
      ApplicationFormSliceDefault,
      CardGridSlice,
      CardGridSliceDefaultPrimary,
      CardGridSliceDefaultItem,
      CardGridSliceVariation,
      CardGridSliceDefault,
      CenteredTextSlice,
      CenteredTextSliceDefaultPrimary,
      CenteredTextSliceVariation,
      CenteredTextSliceDefault,
      FeatureGridSlice,
      FeatureGridSliceDefaultPrimary,
      FeatureGridSliceDefaultItem,
      FeatureGridSliceNoBackgroundImagesPrimary,
      FeatureGridSliceNoBackgroundImagesItem,
      FeatureGridSliceVariation,
      FeatureGridSliceDefault,
      FeatureGridSliceNoBackgroundImages,
      FeatureRowSlice,
      FeatureRowSliceDefaultPrimary,
      FeatureRowSliceDefaultItem,
      FeatureRowSliceVariation,
      FeatureRowSliceDefault,
      FullWidthAccordionSlice,
      FullWidthAccordionSliceDefaultPrimary,
      FullWidthAccordionSliceDefaultItem,
      FullWidthAccordionSliceVariation,
      FullWidthAccordionSliceDefault,
      FullWidthImageSlice,
      FullWidthImageSliceDefaultPrimary,
      FullWidthImageSliceVariation,
      FullWidthImageSliceDefault,
      HeroBannerSlice,
      HeroBannerSliceDefaultPrimary,
      HeroBannerSliceTextLeftPrimary,
      HeroBannerSliceTextRightPrimary,
      HeroBannerSliceVariation,
      HeroBannerSliceDefault,
      HeroBannerSliceTextLeft,
      HeroBannerSliceTextRight,
      ImageAndAccordionRowSlice,
      ImageAndAccordionRowSliceDefaultPrimary,
      ImageAndAccordionRowSliceDefaultItem,
      ImageAndAccordionRowSliceVariation,
      ImageAndAccordionRowSliceDefault,
      ImageAndBulletListSlice,
      ImageAndBulletListSliceDefaultPrimary,
      ImageAndBulletListSliceDefaultItem,
      ImageAndBulletListSliceVariation,
      ImageAndBulletListSliceDefault,
      ImageAndCallToActionSlice,
      ImageAndCallToActionSliceDefaultPrimary,
      ImageAndCallToActionSliceVariation,
      ImageAndCallToActionSliceDefault,
      ImageBannerSlice,
      ImageBannerSliceDefaultItem,
      ImageBannerSliceVariation,
      ImageBannerSliceDefault,
      ImageSliderSlice,
      ImageSliderSliceDefaultPrimary,
      ImageSliderSliceDefaultItem,
      ImageSliderSliceTextBottomPrimary,
      ImageSliderSliceTextBottomItem,
      ImageSliderSliceTextCenterPrimary,
      ImageSliderSliceTextCenterItem,
      ImageSliderSliceVariation,
      ImageSliderSliceDefault,
      ImageSliderSliceTextBottom,
      ImageSliderSliceTextCenter,
      TimeLineSlice,
      TimeLineSliceDefaultPrimary,
      TimeLineSliceDefaultItem,
      TimeLineSliceVariation,
      TimeLineSliceDefault,
      WheelSlice,
      WheelSliceDefaultPrimary,
      WheelSliceDefaultItem,
      WheelSliceVariation,
      WheelSliceDefault,
    };
  }
}
