// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  application_card: dynamic(() => import("./ApplicationCard")),
  application_form: dynamic(() => import("./ApplicationForm")),
  card_grid: dynamic(() => import("./CardGrid")),
  centered_text: dynamic(() => import("./CenteredText")),
  feature_grid: dynamic(() => import("./FeatureGrid")),
  feature_row: dynamic(() => import("./FeatureRow")),
  full_width_accordion: dynamic(() => import("./FullWidthAccordion")),
  full_width_image: dynamic(() => import("./FullWidthImage")),
  hero_banner: dynamic(() => import("./HeroBanner")),
  image_and_accordion_row: dynamic(() => import("./ImageAndAccordionRow")),
  image_and_bullet_list: dynamic(() => import("./ImageAndBulletList")),
  image_and_call_to_action: dynamic(() => import("./ImageAndCallToAction")),
  image_banner: dynamic(() => import("./ImageBanner")),
  image_slider: dynamic(() => import("./ImageSlider")),
  time_line: dynamic(() => import("./TimeLine")),
  wheel: dynamic(() => import("./Wheel")),
};
