// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  card_grid: dynamic(() => import("./CardGrid")),
  feature_grid: dynamic(() => import("./FeatureGrid")),
  feature_row: dynamic(() => import("./FeatureRow")),
  image_and_accordion_row: dynamic(() => import("./ImageAndAccordionRow")),
  image_and_bullet_list: dynamic(() => import("./ImageAndBulletList")),
  image_banner: dynamic(() => import("./ImageBanner")),
  image_slider: dynamic(() => import("./ImageSlider")),
  rich_text: dynamic(() => import("./RichText")),
};
